name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Backend
        run: |
          cd backend
          npm install
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Build Docker Images
        run: docker-compose build
      - name: Save Docker Images
        run: |
          docker save -o backend.tar task-manager_backend
          docker save -o frontend.tar task-manager_frontend
          docker save -o mysql.tar mysql:8.0
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            backend.tar
            frontend.tar
            mysql.tar
            docker-compose.yml
            db/init.sql
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://3.110.158.217:8080/job/Task-Manager-Deploy/build?token=${{ secrets.JENKINS_TOKEN }}" \
          -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
