name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Install Frontend Dependencies
        run: cd frontend && npm install && npm run build

      - name: Build Docker Images
        run: |
          docker compose build
          docker images  # Log image names for debugging

      - name: Save Docker Images
        run: |
          docker save -o backend.tar task-manager_backend || echo "Failed to save backend.tar"
          docker save -o frontend.tar task-manager_frontend || echo "Failed to save frontend.tar"
          docker save -o mysql.tar mysql:8.0 || echo "Failed to save mysql.tar"

      - name: Verify Files Exist
        run: |
          ls -l backend.tar frontend.tar mysql.tar docker-compose.yml db/init.sql || echo "Required files are missing"

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend.tar
            frontend.tar
            mysql.tar
            docker-compose.yml
            db/init.sql

      - name: Trigger Jenkins Build
        run: |
          curl -v -X POST "http://3.110.158.217:8080/job/Task-Manager-Deploy/build?token=${{ secrets.JENKINS_TOKEN }}" \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"