name: Test Upload

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Test File
        run: echo "Test content" > test.txt
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt
